name: PlatformIO CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
#      - name: Change to Project Directory
#        run: cd SRC/MBusinoAP/  # Ersetzen Sie dies durch den Pfad zu Ihrem Projekt, falls erforderlich
      - name: Build PlatformIO Project
        run: pio run